FROM node:20-alpine

WORKDIR /app

# Install pnpm — pinned to the version in package.json's "packageManager" field.
# Leaving this unpinned broke the build on 2026-09-04: npm pulled a newer pnpm
# that verifies package-manager identity against the lockfile and failed with
# ERR_PNPM_PNPM_ENGINE_IDENTITY_UNVERIFIABLE, because @pnpm/exe.linux-x64 is not
# in a lockfile generated by pnpm 10.4.1.
RUN npm install -g pnpm@10.4.1

# Copy package files and patches (needed for pnpm install)
COPY package.json pnpm-lock.yaml ./
COPY patches/ ./patches/

# Install dependencies (allow lockfile updates to prevent CI failures)
RUN pnpm install --no-frozen-lockfile

# Copy source code
COPY . .

# Build the application (force fresh build by removing ALL pre-built artifacts)
RUN rm -rf dist/ && pnpm build

# Set production environment
ENV NODE_ENV=production

# Expose port
EXPOSE 3000

# Start the application using the crypto-patching wrapper
CMD ["node", "start.mjs"]
