import { createContext, useContext, useEffect, useState, ReactNode } from "react";
import { trpc } from "@/lib/trpc";

// ─── Translation Dictionaries ─────────────────────────────────────────────────

const translations = {
  ru: {
    // Navigation
    nav_home: "Главная",
    nav_transactions: "Записи",
    nav_reports: "Отчёты",
    nav_family: "Семья",
    nav_settings: "Ещё",

    // Home
    greeting: "Привет,",
    user_fallback: "Пользователь",
    total_balance: "Общий баланс",
    family_balance: "Семейный баланс",
    income: "Доходы",
    expenses: "Расходы",
    voice_input: "Голосовой ввод",
    recent_records: "Последние записи",
    all_records: "Все →",
    no_records: "Нет записей. Начните с голосового ввода!",
    transaction_label: "Транзакция",
    confirm_transaction: "Подтвердите транзакцию",
    new_transaction: "Новая транзакция",
    recognized: "Распознано:",
    initializing: "Инициализация...",
    authorizing: "Авторизация...",
    open_via_telegram: "Откройте приложение через Telegram бота",
    voice_finance_tracker: "Голосовой финансовый трекер",

    // Transaction form
    expense: "Расход",
    income_btn: "Доход",
    amount: "Сумма",
    currency: "Валюта",
    will_convert_to: "будет конвертировано в",
    category: "Категория",
    select_category: "Выберите категорию",
    description: "Описание",
    description_placeholder: "Описание транзакции",
    date: "Дата",
    personal: "Личное",
    family: "Семейное",
    select_group: "Выберите группу",
    cancel: "Отмена",
    save: "Сохранить",
    add: "Добавить",
    enter_amount: "Введите сумму",
    select_category_error: "Выберите категорию",
    transaction_added: "Транзакция добавлена",
    transaction_updated: "Транзакция обновлена",

    // Transactions page
    transactions_title: "Транзакции",
    all: "Все",
    filter_expense: "Расходы",
    filter_income: "Доходы",
    no_transactions: "Нет транзакций",
    edit: "Редактировать",
    delete: "Удалить",
    confirm_delete: "Удалить транзакцию?",
    confirm_delete_desc: "Это действие нельзя отменить.",
    delete_confirm: "Удалить",
    transaction_deleted: "Транзакция удалена",
    family_badge: "Семья",

    // Reports
    reports_title: "Отчёты",
    week: "Неделя",
    month: "Месяц",
    year: "Год",
    all_time: "Всё",
    balance: "Баланс",
    by_category: "По категориям",
    no_data: "Нет данных за выбранный период",
    export_csv: "CSV",
    csv_download: "Скачать файл",
    csv_send_telegram: "Отправить в Telegram",
    csv_preview: "Предпросмотр",
    csv_sent_telegram: "CSV отправлен в Telegram!",
    csv_downloaded: "CSV скачан",
    csv_rows: "записей",
    trends: "Тренды",
    this_month: "Этот месяц",
    last_month: "Прошлый месяц",
    this_month_vs_last_month: "Этот месяц по сравнению с прошлым",
    top_spending_categories: "Топ категорий расходов",
    no_trend_data: "Нет данных о расходах за этот или прошлый месяц",

    // Family
    family_title: "Семейный бюджет",
    your_group: "Ваша группа",
    invite_code: "Код приглашения",
    members: "Участники",
    leave_group: "Покинуть группу",
    create_group: "Создать группу",
    join_group: "Войти по коду",
    group_name: "Название группы",
    enter_invite_code: "Введите код приглашения",
    create: "Создать",
    join: "Войти",
    no_family_group: "У вас нет семейной группы",
    create_or_join: "Создайте новую или войдите по коду приглашения",
    leave_confirm: "Покинуть группу?",
    leave_confirm_desc: "Вы покинете семейную группу. Ваши транзакции останутся.",
    leave_btn: "Покинуть",
    joined_group: "Вы вступили в группу",
    left_group: "Вы покинули группу",
    copied: "Скопировано!",
    copy_code: "Скопировать код",
    owner_badge: "Владелец",

    // Settings
    settings_title: "Настройки",
    profile_section_title: "Профиль",
    profile_name_placeholder: "Ваше имя",
    profile_save: "Сохранить профиль",
    profile_change_avatar: "Изменить фото профиля",
    profile_avatar_invalid: "Выберите корректное изображение",
    interface_language: "Язык интерфейса",
    default_currency: "Валюта по умолчанию",
    categories: "Категории",
    add_category: "Добавить",
    your_categories: "Ваши категории",
    preset_categories: "Стандартные",
    about: "О приложении",
    about_text: "CA$HUAL — голосовой финансовый трекер для Telegram. Диктуйте расходы и доходы голосом на русском, азербайджанском или английском языке.",
    logout: "Выйти",
    danger_zone: "Опасная зона",
    delete_all_data: "Удалить все данные",
    delete_all_data_desc: "Удалить все транзакции и пользовательские категории. Это действие необратимо.",
    delete_save_csv_prompt: "Хотите сохранить копию данных в CSV перед удалением?",
    save_csv_first: "Сначала сохранить CSV",
    delete_without_saving: "Удалить без сохранения",
    save_csv_title: "Сохранить данные",
    save_csv_desc: "Выберите способ сохранения CSV-файла с вашими данными:",
    proceed_to_delete: "Продолжить удаление",
    final_delete_title: "Вы уверены?",
    final_delete_desc: "Все транзакции и пользовательские категории будут удалены безвозвратно. Это действие нельзя отменить.",
    confirm_delete_all: "Удалить всё",
    all_data_deleted: "Все данные удалены",
    settings_saved: "Настройки сохранены",
    new_category: "Новая категория",
    category_name: "Название",
    icon: "Иконка",
    color: "Цвет",
    income_expense: "Доход и расход",
    expense_only: "Только расход",
    income_only: "Только доход",
    category_created: "Категория создана",
    category_deleted: "Категория удалена",
    login_to_view: "Войдите для просмотра",
    default_budget: "Бюджет по умолчанию",
    default_budget_personal: "Личный",
    default_budget_family: "Семейный",
    default_budget_desc: "Какой бюджет выбирать по умолчанию при добавлении транзакции",
    reminders: "Напоминания",
    reminders_desc: "Вечернее напоминание и утренний итог расходов в Telegram",

    // Family scope in reports
    scope_personal: "Мои",
    scope_partner: "Партнёра",
    scope_all: "Все вместе",
    family_report_label: "Семейный отчёт",
    family_transactions_label: "Семейные транзакции",

    // Family page (translated)
    family_mode: "Семейный режим",
    group_members: "Участники группы",
    show_members: "Показать участников",
    hide_members: "Скрыть участников",
    member: "Участник",
    no_family_groups: "Нет семейных групп",
    create_or_join_hint: "Создайте группу или присоединитесь по коду приглашения",
    group_name_placeholder: "Название группы",
    leave_group_title: "Покинуть группу?",
    leave_group_description: "Вы больше не сможете видеть семейные транзакции этой группы.",
    group_created: "Группа создана!",
    group_joined: "Вы присоединились к группе!",
    group_left: "Вы покинули группу",
    code_copied: "Код скопирован!",

    // Permissions
    show_permissions: "Настроить доступ",
    hide_permissions: "Скрыть настройки доступа",
    permissions_title: "Кто видит мои расходы",
    permissions_description: "Управляйте тем, кто из участников группы может видеть ваши расходы в семейных отчётах.",
    can_see_expenses: "Видит мои расходы",
    cannot_see_expenses: "Не видит мои расходы",
    permission_updated: "Настройки доступа обновлены",

    // Business / Work
    nav_business: "Работа",
    work: "Работа",
    work_badge: "Работа",
    business_title: "Рабочие бюджеты",
    business_desc: "Создайте отдельные бюджеты для каждой компании или проекта. Помечайте транзакции как рабочие расходы.",
    business_add_group: "Добавить",
    business_new_group: "Новый рабочий бюджет",
    business_edit_group: "Редактировать бюджет",
    business_group_name_placeholder: "Название компании или проекта",
    no_business_groups: "Нет рабочих бюджетов",
    business_group_created: "Бюджет создан!",
    business_group_updated: "Бюджет обновлён",
    business_group_deleted: "Бюджет удалён",
    business_delete_confirm: "Удалить рабочий бюджет?",
    business_delete_desc: "Транзакции останутся, но больше не будут привязаны к этому бюджету.",
    select_business_group: "Выберите компанию",
    select_business_group_hint: "Выберите компанию для этого расхода",

    // Receipt
    scan_receipt: "Сканировать чек",
    receipt_title: "Распознать чек",
    receipt_desc: "Сфотографируйте чек или скриншот банковской транзакции",
    take_photo: "Сфотографировать",
    upload_image: "Загрузить фото",
    processing_receipt: "Распознаю чек...",
    processing_receipt_desc: "Анализирую изображение с помощью ИИ",
    receipt_recognized: "Чек распознан",
    voice_recognized: "Голос распознан",
    transactions_found: "транзакций найдено",
    selected: "выбрано",
    bulk_budget: "Бюджет для всех",
    apply_to_all: "Применить ко всем",
    budget_applied_to_all: "Бюджет применён ко всем",
    no_transactions_selected: "Не выбрано ни одной транзакции",
    tap_to_change_budget: "Нажмите для смены бюджета",
    review_carefully: "Проверьте внимательно — некоторые позиции с низкой уверенностью",
    receipt_error: "Не удалось распознать чек",
    confidence: "Точность",
    confidence_high: "Высокая",
    confidence_medium: "Средняя",
    confidence_low: "Низкая",
    review_and_confirm: "Проверьте и подтвердите данные транзакции:",
    receipt_desc_multi: "Сфотографируйте или загрузите изображения чеков и банковских выписок",
    upload_images: "Загрузить фото",
    process_images: "Обработать",
    images_processed: "фото обработано",
    potential_duplicates: "возможных дубликатов",
    duplicates_unchecked: "Дубликаты не выбраны по умолчанию. Отметьте, если хотите сохранить.",
    duplicate_exists: "Возможный дубликат",
    duplicates_skipped: "дубликатов пропущено",
    image_too_large: "Изображение слишком большое (макс 10МБ)",
    no_transactions_found: "Транзакции не найдены на изображениях",

    // AI Advisor
    nav_ai: "ИИ",
    ai_title: "CA$HUAL AI",
    ai_subtitle: "Финансовый ассистент",
    ai_welcome_title: "Спросите о финансах",
    ai_welcome_desc: "Задайте вопрос голосом или текстом — ИИ проанализирует ваши данные и даст ответ",
    ai_suggestion_1: "Сколько я потратил за последний месяц?",
    ai_suggestion_2: "Как мне сократить расходы?",
    ai_suggestion_3: "Покажи расходы по категориям",
    ai_thinking: "Анализирую...",
    ai_error: "Ошибка ИИ. Попробуйте ещё раз.",
    ai_input_placeholder: "Спросите о финансах...",
    ai_recording: "Запись",
    ai_recording_too_short: "Запись слишком короткая",
    ai_no_mic: "Нет доступа к микрофону",
    today: "Сегодня",
    yesterday: "Вчера",

    // Apple Wallet
    wallet_title: "Apple Wallet",
    wallet_connect: "Подключить Apple Wallet",
    wallet_connected: "Apple Wallet подключён",
    wallet_description: "Автоматически записывайте транзакции с Apple Pay через iOS Shortcuts",
    wallet_token_generated: "Токен создан",
    wallet_setup_title: "Настройка iOS Shortcut",
    wallet_step_1: "Откройте приложение Shortcuts → Автоматизация → + → Транзакция",
    wallet_step_2: "Выберите \"Любая карта\"",
    wallet_step_3: "Добавьте действие \"Получить содержимое URL\"",
    wallet_step_4: "Настройте запрос с данными ниже:",
    wallet_url_label: "URL",
    wallet_token_label: "Токен",
    wallet_copy_url: "Скопировать URL",
    wallet_copy_token: "Скопировать токен",
    wallet_copied: "Скопировано!",
    wallet_method: "Метод: POST",
    wallet_headers: "Заголовки:",
    wallet_body: "Тело запроса (JSON):",
    wallet_body_hint: "Используйте переменные Shortcuts для amount, merchant, currency",
    wallet_regenerate: "Сгенерировать новый токен",
    wallet_hide_instructions: "Скрыть инструкции",
    wallet_show_instructions: "Показать инструкции",
    wallet_open_shortcuts: "Открыть Shortcuts",
    wallet_quick_setup: "Быстрая настройка (3 шага):",
    wallet_step_1_simple: "Выберите триггер \"Транзакция\" → Любая карта",
    wallet_step_2_simple: "Добавьте действие \"Получить содержимое URL\" и вставьте скопированную ссылку",
    wallet_step_3_simple: "Готово! Каждая оплата Apple Pay будет записываться автоматически",
    wallet_step_1_new: "Откройте Shortcuts → Автоматизация → + → Транзакция → Любая карта",
    wallet_step_2_new: "Добавьте действие 'Получить содержимое URL' и вставьте скопированную ссылку",
    wallet_step_3_new: "В URL замените AMOUNT, MERCHANT и CURRENCY_CODE на переменные из триггера",
    wallet_copy_link: "Скопировать ссылку для Shortcuts",
    wallet_link_copied_toast: "Ссылка скопирована! Откройте Shortcuts на iPhone и создайте автоматизацию",
    wallet_hide_details: "Скрыть детали",
    wallet_show_details: "Показать детали",
  },

  az: {
    // Navigation
    nav_home: "Ana səhifə",
    nav_transactions: "Əməliyyatlar",
    nav_reports: "Hesabatlar",
    nav_family: "Ailə",
    nav_settings: "Daha çox",

    // Home
    greeting: "Salam,",
    user_fallback: "İstifadəçi",
    total_balance: "Ümumi balans",
    family_balance: "Ailə balansı",
    income: "Gəlirlər",
    expenses: "Xərclər",
    voice_input: "Səsli giriş",
    recent_records: "Son qeydlər",
    all_records: "Hamısı →",
    no_records: "Qeyd yoxdur. Səsli girişlə başlayın!",
    transaction_label: "Əməliyyat",
    confirm_transaction: "Əməliyyatı təsdiqləyin",
    new_transaction: "Yeni əməliyyat",
    recognized: "Tanındı:",
    initializing: "Başlanır...",
    authorizing: "Giriş edilir...",
    open_via_telegram: "Tətbiqi Telegram botu vasitəsilə açın",
    voice_finance_tracker: "Səsli maliyyə izləyicisi",

    // Transaction form
    expense: "Xərc",
    income_btn: "Gəlir",
    amount: "Məbləğ",
    currency: "Valyuta",
    will_convert_to: "çevriləcək",
    category: "Kateqoriya",
    select_category: "Kateqoriya seçin",
    description: "Təsvir",
    description_placeholder: "Əməliyyatın təsviri",
    date: "Tarix",
    personal: "Şəxsi",
    family: "Ailə",
    select_group: "Qrup seçin",
    cancel: "Ləğv et",
    save: "Saxla",
    add: "Əlavə et",
    enter_amount: "Məbləği daxil edin",
    select_category_error: "Kateqoriya seçin",
    transaction_added: "Əməliyyat əlavə edildi",
    transaction_updated: "Əməliyyat yeniləndi",

    // Transactions page
    transactions_title: "Əməliyyatlar",
    all: "Hamısı",
    filter_expense: "Xərclər",
    filter_income: "Gəlirlər",
    no_transactions: "Əməliyyat yoxdur",
    edit: "Redaktə et",
    delete: "Sil",
    confirm_delete: "Əməliyyat silinsin?",
    confirm_delete_desc: "Bu əməliyyat geri qaytarıla bilməz.",
    delete_confirm: "Sil",
    transaction_deleted: "Əməliyyat silindi",
    family_badge: "Ailə",

    // Reports
    reports_title: "Hesabatlar",
    week: "Həftə",
    month: "Ay",
    year: "İl",
    all_time: "Hamısı",
    balance: "Balans",
    by_category: "Kateqoriyaya görə",
    no_data: "Seçilmiş dövr üçün məlumat yoxdur",
    export_csv: "CSV",
    csv_download: "Faylı yüklə",
    csv_send_telegram: "Telegram-a göndər",
    csv_preview: "Ön baxış",
    csv_sent_telegram: "CSV Telegram-a göndərildi!",
    csv_downloaded: "CSV yükləndi",
    csv_rows: "qeyd",
    trends: "Trendlər",
    this_month: "Bu ay",
    last_month: "Keçən ay",
    this_month_vs_last_month: "Bu ay keçən ayla müqayisədə",
    top_spending_categories: "Ən çox xərclənən kateqoriyalar",
    no_trend_data: "Bu və ya keçən ay üçün xərc məlumatı yoxdur",

    // Family
    family_title: "Ailə büdcəsi",
    your_group: "Qrupunuz",
    invite_code: "Dəvət kodu",
    members: "Üzvlər",
    leave_group: "Qrupdan çıx",
    create_group: "Qrup yarat",
    join_group: "Kodla qoşul",
    group_name: "Qrupun adı",
    enter_invite_code: "Dəvət kodunu daxil edin",
    create: "Yarat",
    join: "Qoşul",
    no_family_group: "Ailə qrupunuz yoxdur",
    create_or_join: "Yeni qrup yaradın və ya dəvət kodu ilə qoşulun",
    leave_confirm: "Qrupdan çıxılsın?",
    leave_confirm_desc: "Siz ailə qrupundan çıxacaqsınız. Əməliyyatlarınız qalacaq.",
    leave_btn: "Çıx",
    joined_group: "Qrupa qoşuldunuz",
    left_group: "Qrupdan çıxdınız",
    copied: "Kopyalandı!",
    copy_code: "Kodu kopyala",
    owner_badge: "Sahib",

    // Settings
    settings_title: "Parametrlər",
    profile_section_title: "Profil",
    profile_name_placeholder: "Adınız",
    profile_save: "Profili saxla",
    profile_change_avatar: "Profil şəklini dəyiş",
    profile_avatar_invalid: "Düzgün şəkil seçin",
    interface_language: "İnterfeys dili",
    default_currency: "Standart valyuta",
    categories: "Kateqoriyalar",
    add_category: "Əlavə et",
    your_categories: "Sizin kateqoriyalar",
    preset_categories: "Standart",
    about: "Proqram haqqında",
    about_text: "CA$HUAL — Telegram üçün səsli maliyyə izləyicisi. Xərclərinizi və gəlirlərinizi Azərbaycan, rus və ya ingilis dilində diktə edin.",
    logout: "Çıxış",
    danger_zone: "Təhlükəli zona",
    delete_all_data: "Bütün məlumatları sil",
    delete_all_data_desc: "Bütün əməliyyatlar və istifadəçi kateqoriyaları silinəcək. Bu əməliyyat geri qaytarıla bilməz.",
    delete_save_csv_prompt: "Silmədən əvvəl məlumatların CSV surətini saxlamaq istəyirsiniz?",
    save_csv_first: "Əvvəlcə CSV saxla",
    delete_without_saving: "Saxlamadan sil",
    save_csv_title: "Məlumatları saxla",
    save_csv_desc: "Məlumatlarınızla CSV faylını saxlamaq üçün üsul seçin:",
    proceed_to_delete: "Silməyə davam et",
    final_delete_title: "Əminsiniz?",
    final_delete_desc: "Bütün əməliyyatlar və istifadəçi kateqoriyaları birdəfəlik silinəcək. Bu əməliyyatı geri qaytarmaq mümkün deyil.",
    confirm_delete_all: "Hamısını sil",
    all_data_deleted: "Bütün məlumatlar silindi",
    settings_saved: "Parametrlər saxlandı",
    new_category: "Yeni kateqoriya",
    category_name: "Ad",
    icon: "İkon",
    color: "Rəng",
    income_expense: "Gəlir və xərc",
    expense_only: "Yalnız xərc",
    income_only: "Yalnız gəlir",
    category_created: "Kateqoriya yaradıldı",
    category_deleted: "Kateqoriya silindi",
    login_to_view: "Baxmaq üçün daxil olun",
    default_budget: "Standart büdcə",
    default_budget_personal: "Şəxsi",
    default_budget_family: "Ailə",
    default_budget_desc: "Əməliyyat əlavə edərkən hansı büdcəni standart seçmək",
    reminders: "Xatırlatmalar",
    reminders_desc: "Telegram-da axşam xatırlatması və səhər xərc xülasəsi",

    // Family scope in reports
    scope_personal: "Mənim",
    scope_partner: "Partnerin",
    scope_all: "Hamısı birlikdə",
    family_report_label: "Ailə hesabatı",
    family_transactions_label: "Ailə əməliyyatları",

    // Family page (translated)
    family_mode: "Ailə rejimi",
    group_members: "Qrup üzvləri",
    show_members: "Üzvləri göstər",
    hide_members: "Üzvləri gizlət",
    member: "Üzv",
    no_family_groups: "Ailə qrupu yoxdur",
    create_or_join_hint: "Yeni qrup yaradın və ya dəvət kodu ilə qoşulun",
    group_name_placeholder: "Qrupun adı",
    leave_group_title: "Qrupdan çıxılsın?",
    leave_group_description: "Siz bu qrupun ailə əməliyyatlarını görə bilməyəcəksiniz.",
    group_created: "Qrup yaradıldı!",
    group_joined: "Qrupa qoşuldunuz!",
    group_left: "Qrupdan çıxdınız",
    code_copied: "Kod kopyalandı!",

    // Permissions
    show_permissions: "Girişi tənzimlə",
    hide_permissions: "Giriş parametrlərini gizlət",
    permissions_title: "Xərclərimə kim baxa bilər",
    permissions_description: "Qrup üzvlərindən kimin ailə hesabatlarında xərclərinizi görə biləcəyini idarə edin.",
    can_see_expenses: "Xərclərimə baxa bilər",
    cannot_see_expenses: "Xərclərimə baxa bilməz",
    permission_updated: "Giriş parametrləri yeniləndi",

    // Business / Work
    nav_business: "İş",
    work: "İş",
    work_badge: "İş",
    business_title: "İş büḑcələri",
    business_desc: "Hər şirkət və ya layihə üçün ayrıca büḑcə yarat. Əməliyyatları iş xərci kimi qeyd edin.",
    business_add_group: "Əlavə et",
    business_new_group: "Yeni iş büḑcəsi",
    business_edit_group: "Büḑcəni dəyiş",
    business_group_name_placeholder: "Şirkət və ya layihə adı",
    no_business_groups: "İş büḑcəsi yoxdur",
    business_group_created: "Büḑcə yaradıldı!",
    business_group_updated: "Büḑcə yeniləndi",
    business_group_deleted: "Büḑcə silindi",
    business_delete_confirm: "İş büḑcəsi silinsin?",
    business_delete_desc: "Əməliyyatlar qalar, lakin bu büḑcəyə bağlı olmayacaq.",
    select_business_group: "Şirkəti seçin",
    select_business_group_hint: "Bu xərc üçün şirkəti seçin",

    // Receipt
    scan_receipt: "Çeki skan et",
    receipt_title: "Çeki tanı",
    receipt_desc: "Çekin və ya bank əməliyyatının ekran görüntüsünü çəkin",
    take_photo: "Foto çək",
    upload_image: "Şəkil yüklə",
    processing_receipt: "Çek tanınır...",
    processing_receipt_desc: "Süni intellekt ilə şəkil analiz edilir",
    receipt_recognized: "Çek tanındı",
    voice_recognized: "Səs tanındı",
    transactions_found: "əməliyyat tapıldı",
    selected: "seçildi",
    bulk_budget: "Hamısı üçün büdcə",
    apply_to_all: "Hamısına tətbiq et",
    budget_applied_to_all: "Büdcə hamısına tətbiq edildi",
    no_transactions_selected: "Heç bir əməliyyat seçilməyib",
    tap_to_change_budget: "Büdcəni dəyişmək üçün basın",
    review_carefully: "Diqqətlə yoxlayın — bəzi maddələr aşağı etibar səviyyəsinə malikdir",
    receipt_error: "Çeki tanımaq mümkün olmadı",
    confidence: "Dəqiqlik",
    confidence_high: "Yüksək",
    confidence_medium: "Orta",
    confidence_low: "Aşağı",
    review_and_confirm: "Əməliyyat məlumatlarını yoxlayın və təsdiqləyin:",
    receipt_desc_multi: "Çeklərin və bank çıxarışlarının şəkillərini çəkin və ya yükləyin",
    upload_images: "Şəkillər yüklə",
    process_images: "Emal et",
    images_processed: "şəkil emal edildi",
    potential_duplicates: "ehtimal olunan dublikat",
    duplicates_unchecked: "Dublikatlar defolt olaraq seçilməyib. Saxlamaq istəyirsinizsə işarələyin.",
    duplicate_exists: "Ehtimal olunan dublikat",
    duplicates_skipped: "dublikat keçildi",
    image_too_large: "Şəkil çox böyükdür (maks 10MB)",
    no_transactions_found: "Şəkillərdə əməliyyat tapılmadı",

    // AI Advisor
    nav_ai: "AI",
    ai_title: "CA$HUAL AI",
    ai_subtitle: "Maliyyə köməkçisi",
    ai_welcome_title: "Maliyyə haqqında soruşun",
    ai_welcome_desc: "Səslə və ya mətnlə sual verin — AI məlumatlarınızı təhlil edəcək",
    ai_suggestion_1: "Son ay nə qədər xərcləmişəm?",
    ai_suggestion_2: "Xərcləri necə azalda bilərəm?",
    ai_suggestion_3: "Kateqoriyalara görə xərcləri göstər",
    ai_thinking: "Təhlil edirəm...",
    ai_error: "AI xətası. Yenidən cəhd edin.",
    ai_input_placeholder: "Maliyyə haqqında soruşun...",
    ai_recording: "Yazılır",
    ai_recording_too_short: "Yazı çox qısadır",
    ai_no_mic: "Mikrofona giriş yoxdur",
    today: "Bu gün",
    yesterday: "Dünən",

    // Apple Wallet
    wallet_title: "Apple Wallet",
    wallet_connect: "Apple Wallet qoş",
    wallet_connected: "Apple Wallet qoşulub",
    wallet_description: "iOS Shortcuts vasitəsilə Apple Pay əməliyyatlarını avtomatik qeyd edin",
    wallet_token_generated: "Token yaradıldı",
    wallet_setup_title: "iOS Shortcut quraşdırması",
    wallet_step_1: "Shortcuts tətbiqini açın → Avtomatlaşdırma → + → Əməliyyat",
    wallet_step_2: "\"Hər hansı kart\" seçin",
    wallet_step_3: "\"URL məzmununu al\" əməliyyatını əlavə edin",
    wallet_step_4: "Aşağıdakı məlumatlarla sorğunu quraşdırın:",
    wallet_url_label: "URL",
    wallet_token_label: "Token",
    wallet_copy_url: "URL kopyala",
    wallet_copy_token: "Token kopyala",
    wallet_copied: "Kopyalandı!",
    wallet_method: "Metod: POST",
    wallet_headers: "Başlıqlar:",
    wallet_body: "Sorğu gövdəsi (JSON):",
    wallet_body_hint: "amount, merchant, currency üçün Shortcuts dəyişənlərini istifadə edin",
    wallet_regenerate: "Yeni token yarat",
    wallet_hide_instructions: "Təlimatları gizlət",
    wallet_show_instructions: "Təlimatları göstər",
    wallet_open_shortcuts: "Shortcuts aç",
    wallet_quick_setup: "Sürətli quraşdırma (3 addım):",
    wallet_step_1_simple: "\"Tranzaksiya\" triggeri seçin → Hər hansı kart",
    wallet_step_2_simple: "\"URL məzmununu al\" əməliyyatını əlavə edin və kopyalanmış linki yapışdırın",
    wallet_step_3_simple: "Hazırdır! Hər Apple Pay ödənişi avtomatik qeyd olunacaq",
    wallet_step_1_new: "Shortcuts açın → Avtomatlaşdırma → + → Tranzaksiya → İstənilən kart",
    wallet_step_2_new: "'URL məzmununu al' əməliyyatı əlavə edin və kopyalanmış linki yapışdırın",
    wallet_step_3_new: "URL-də AMOUNT, MERCHANT və CURRENCY_CODE-u triggerdən dəyişənlərlə əvəz edin",
    wallet_copy_link: "Shortcuts üçün linki kopyala",
    wallet_link_copied_toast: "Link kopyalandı! iPhone-da Shortcuts açın və avtomatlaşdırma yaradın",
    wallet_hide_details: "Detalları gizlət",
    wallet_show_details: "Detalları göstər",
  },

  en: {
    // Navigation
    nav_home: "Home",
    nav_transactions: "Records",
    nav_reports: "Reports",
    nav_family: "Family",
    nav_settings: "More",

    // Home
    greeting: "Hello,",
    user_fallback: "User",
    total_balance: "Total Balance",
    family_balance: "Family Balance",
    income: "Income",
    expenses: "Expenses",
    voice_input: "Voice Input",
    recent_records: "Recent Records",
    all_records: "All →",
    no_records: "No records yet. Start with voice input!",
    transaction_label: "Transaction",
    confirm_transaction: "Confirm Transaction",
    new_transaction: "New Transaction",
    recognized: "Recognized:",
    initializing: "Initializing...",
    authorizing: "Authorizing...",
    open_via_telegram: "Open the app through Telegram bot",
    voice_finance_tracker: "Voice Finance Tracker",

    // Transaction form
    expense: "Expense",
    income_btn: "Income",
    amount: "Amount",
    currency: "Currency",
    will_convert_to: "will be converted to",
    category: "Category",
    select_category: "Select category",
    description: "Description",
    description_placeholder: "Transaction description",
    date: "Date",
    personal: "Personal",
    family: "Family",
    select_group: "Select group",
    cancel: "Cancel",
    save: "Save",
    add: "Add",
    enter_amount: "Enter amount",
    select_category_error: "Select a category",
    transaction_added: "Transaction added",
    transaction_updated: "Transaction updated",

    // Transactions page
    transactions_title: "Transactions",
    all: "All",
    filter_expense: "Expenses",
    filter_income: "Income",
    no_transactions: "No transactions",
    edit: "Edit",
    delete: "Delete",
    confirm_delete: "Delete transaction?",
    confirm_delete_desc: "This action cannot be undone.",
    delete_confirm: "Delete",
    transaction_deleted: "Transaction deleted",
    family_badge: "Family",

    // Reports
    reports_title: "Reports",
    week: "Week",
    month: "Month",
    year: "Year",
    all_time: "All",
    balance: "Balance",
    by_category: "By Category",
    no_data: "No data for the selected period",
    export_csv: "CSV",
    csv_download: "Download file",
    csv_send_telegram: "Send to Telegram",
    csv_preview: "Preview",
    csv_sent_telegram: "CSV sent to Telegram!",
    csv_downloaded: "CSV downloaded",
    csv_rows: "rows",
    trends: "Trends",
    this_month: "This Month",
    last_month: "Last Month",
    this_month_vs_last_month: "This month compared with last month",
    top_spending_categories: "Top spending categories",
    no_trend_data: "No expense data for this or last month",

    // Family
    family_title: "Family Budget",
    your_group: "Your Group",
    invite_code: "Invite Code",
    members: "Members",
    leave_group: "Leave Group",
    create_group: "Create Group",
    join_group: "Join by Code",
    group_name: "Group Name",
    enter_invite_code: "Enter invite code",
    create: "Create",
    join: "Join",
    no_family_group: "You have no family group",
    create_or_join: "Create a new one or join with an invite code",
    leave_confirm: "Leave group?",
    leave_confirm_desc: "You will leave the family group. Your transactions will remain.",
    leave_btn: "Leave",
    joined_group: "You joined the group",
    left_group: "You left the group",
    copied: "Copied!",
    copy_code: "Copy code",
    owner_badge: "Owner",

    // Settings
    settings_title: "Settings",
    profile_section_title: "Profile",
    profile_name_placeholder: "Your name",
    profile_save: "Save profile",
    profile_change_avatar: "Change profile photo",
    profile_avatar_invalid: "Choose a valid image",
    interface_language: "Interface Language",
    default_currency: "Default Currency",
    categories: "Categories",
    add_category: "Add",
    your_categories: "Your Categories",
    preset_categories: "Preset",
    about: "About",
    about_text: "CA$HUAL — a voice finance tracker for Telegram. Dictate your expenses and income in Russian, Azerbaijani, or English.",
    logout: "Log Out",
    danger_zone: "Danger Zone",
    delete_all_data: "Delete All Data",
    delete_all_data_desc: "Delete all transactions and custom categories. This action is irreversible.",
    delete_save_csv_prompt: "Would you like to save a CSV backup of your data before deleting?",
    save_csv_first: "Save CSV first",
    delete_without_saving: "Delete without saving",
    save_csv_title: "Save Data",
    save_csv_desc: "Choose how to save your CSV data file:",
    proceed_to_delete: "Proceed to delete",
    final_delete_title: "Are you sure?",
    final_delete_desc: "All transactions and custom categories will be permanently deleted. This action cannot be undone.",
    confirm_delete_all: "Delete everything",
    all_data_deleted: "All data deleted",
    settings_saved: "Settings saved",
    new_category: "New Category",
    category_name: "Name",
    icon: "Icon",
    color: "Color",
    income_expense: "Income & Expense",
    expense_only: "Expense only",
    income_only: "Income only",
    category_created: "Category created",
    category_deleted: "Category deleted",
    login_to_view: "Log in to view",
    default_budget: "Default Budget",
    default_budget_personal: "Personal",
    default_budget_family: "Family",
    default_budget_desc: "Which budget to select by default when adding a transaction",
    reminders: "Reminders",
    reminders_desc: "Evening reminder and morning spending summary in Telegram",

    // Family scope in reports
    scope_personal: "Mine",
    scope_partner: "Partner's",
    scope_all: "All together",
    family_report_label: "Family report",
    family_transactions_label: "Family transactions",

    // Family page (translated)
    family_mode: "Family Mode",
    group_members: "Group Members",
    show_members: "Show Members",
    hide_members: "Hide Members",
    member: "Member",
    no_family_groups: "No family groups",
    create_or_join_hint: "Create a group or join with an invite code",
    group_name_placeholder: "Group name",
    leave_group_title: "Leave group?",
    leave_group_description: "You will no longer see family transactions from this group.",
    group_created: "Group created!",
    group_joined: "You joined the group!",
    group_left: "You left the group",
    code_copied: "Code copied!",

    // Permissions
    show_permissions: "Manage Access",
    hide_permissions: "Hide Access Settings",
    permissions_title: "Who can see my expenses",
    permissions_description: "Control which group members can see your expenses in family reports.",
    can_see_expenses: "Can see my expenses",
    cannot_see_expenses: "Cannot see my expenses",
    permission_updated: "Access settings updated",

    // Business / Work
    nav_business: "Work",
    work: "Work",
    work_badge: "Work",
    business_title: "Work Budgets",
    business_desc: "Create separate budgets for each company or project. Tag transactions as work expenses.",
    business_add_group: "Add",
    business_new_group: "New Work Budget",
    business_edit_group: "Edit Budget",
    business_group_name_placeholder: "Company or project name",
    no_business_groups: "No work budgets yet",
    business_group_created: "Budget created!",
    business_group_updated: "Budget updated",
    business_group_deleted: "Budget deleted",
    business_delete_confirm: "Delete work budget?",
    business_delete_desc: "Transactions will remain but will no longer be linked to this budget.",
    select_business_group: "Select company",
    select_business_group_hint: "Select which company this expense belongs to",

    // Receipt
    scan_receipt: "Scan Receipt",
    receipt_title: "Scan Receipt",
    receipt_desc: "Take a photo of a receipt or a bank transaction screenshot",
    take_photo: "Take Photo",
    upload_image: "Upload Image",
    processing_receipt: "Recognizing receipt...",
    processing_receipt_desc: "Analyzing image with AI",
    receipt_recognized: "Receipt recognized",
    voice_recognized: "Voice recognized",
    transactions_found: "transactions found",
    selected: "selected",
    bulk_budget: "Budget for all",
    apply_to_all: "Apply to all",
    budget_applied_to_all: "Budget applied to all",
    no_transactions_selected: "No transactions selected",
    tap_to_change_budget: "Tap to change budget",
    review_carefully: "Review carefully — some items have low confidence",
    receipt_error: "Could not recognize receipt",
    confidence: "Confidence",
    confidence_high: "High",
    confidence_medium: "Medium",
    confidence_low: "Low",
    review_and_confirm: "Review and confirm transaction details:",
    receipt_desc_multi: "Take photos or upload images of receipts and bank statements",
    upload_images: "Upload Images",
    process_images: "Process",
    images_processed: "images processed",
    potential_duplicates: "potential duplicate(s) found",
    duplicates_unchecked: "Duplicates are unchecked by default. Check them if you want to save anyway.",
    duplicate_exists: "Possible duplicate",
    duplicates_skipped: "duplicates skipped",
    image_too_large: "Image too large (max 10MB)",
    no_transactions_found: "No transactions found in images",

    // AI Advisor
    nav_ai: "AI",
    ai_title: "CA$HUAL AI",
    ai_subtitle: "Financial Assistant",
    ai_welcome_title: "Ask about finances",
    ai_welcome_desc: "Ask a question by voice or text — AI will analyze your data and respond",
    ai_suggestion_1: "How much did I spend last month?",
    ai_suggestion_2: "How can I reduce my expenses?",
    ai_suggestion_3: "Show expenses by category",
    ai_thinking: "Analyzing...",
    ai_error: "AI error. Please try again.",
    ai_input_placeholder: "Ask about finances...",
    ai_recording: "Recording",
    ai_recording_too_short: "Recording too short",
    ai_no_mic: "No microphone access",
    today: "Today",
    yesterday: "Yesterday",

    // Apple Wallet
    wallet_title: "Apple Wallet",
    wallet_connect: "Connect Apple Wallet",
    wallet_connected: "Apple Wallet connected",
    wallet_description: "Automatically log Apple Pay transactions via iOS Shortcuts",
    wallet_token_generated: "Token generated",
    wallet_setup_title: "iOS Shortcut Setup",
    wallet_step_1: "Open Shortcuts app → Automation → + → Transaction",
    wallet_step_2: "Select \"Any Card\"",
    wallet_step_3: "Add action \"Get Contents of URL\"",
    wallet_step_4: "Configure the request with the data below:",
    wallet_url_label: "URL",
    wallet_token_label: "Token",
    wallet_copy_url: "Copy URL",
    wallet_copy_token: "Copy Token",
    wallet_copied: "Copied!",
    wallet_method: "Method: POST",
    wallet_headers: "Headers:",
    wallet_body: "Request body (JSON):",
    wallet_body_hint: "Use Shortcuts variables for amount, merchant, currency",
    wallet_regenerate: "Generate new token",
    wallet_hide_instructions: "Hide instructions",
    wallet_show_instructions: "Show instructions",
    wallet_open_shortcuts: "Open Shortcuts",
    wallet_quick_setup: "Quick setup (3 steps):",
    wallet_step_1_simple: "Select \"Transaction\" trigger → Any Card",
    wallet_step_2_simple: "Add \"Get Contents of URL\" action and paste the copied link",
    wallet_step_3_simple: "Done! Every Apple Pay payment will be logged automatically",
    wallet_step_1_new: "Open Shortcuts → Automation → + → Transaction → Any Card",
    wallet_step_2_new: "Add 'Get Contents of URL' action and paste the copied link",
    wallet_step_3_new: "In the URL, replace AMOUNT, MERCHANT and CURRENCY_CODE with variables from the trigger",
    wallet_copy_link: "Copy link for Shortcuts",
    wallet_link_copied_toast: "Link copied! Open Shortcuts on iPhone and create automation",
    wallet_hide_details: "Hide details",
    wallet_show_details: "Show details",
  },
} as const;

// ─── Category Name Translations ───────────────────────────────────────────────
// Categories are stored canonically in English; this dictionary localizes display names.
export const categoryTranslations: Record<string, { ru: string; az: string; en: string }> = {
  Food:          { ru: "Еда",                az: "Ərzaq",          en: "Food" },
  Transport:     { ru: "Транспорт",          az: "Nəqliyyat",      en: "Transport" },
  Housing:       { ru: "Жильё и дом",        az: "Mənzil və ev",    en: "Housing" },
  Entertainment: { ru: "Развлечения",        az: "Əyləncə",        en: "Entertainment" },
  Health:        { ru: "Здоровье",           az: "Sağlamlıq",      en: "Health" },
  Clothing:      { ru: "Одежда",             az: "Geyim",          en: "Clothing" },
  Education:     { ru: "Образование",        az: "Təhsil",         en: "Education" },
  Restaurants:   { ru: "Рестораны",          az: "Restoranlar",    en: "Restaurants" },
  Communication: { ru: "Связь",              az: "Rabitə",         en: "Communication" },
  Subscriptions: { ru: "Подписки",           az: "Abunəliklər",    en: "Subscriptions" },
  Gifts:         { ru: "Подарки",            az: "Hədiyyələr",     en: "Gifts" },
  Salary:        { ru: "Зарплата",           az: "Maaş",           en: "Salary" },
  Freelance:     { ru: "Фриланс",            az: "Frilansinq",     en: "Freelance" },
  Investments:   { ru: "Инвестиции",         az: "İnvestisiyalar", en: "Investments" },
  Other:         { ru: "Другое",             az: "Digər",          en: "Other" },
  Auto:          { ru: "Авто",               az: "Avto",           en: "Auto" },
  Pets:          { ru: "Питомцы",            az: "Ev heyvanları",  en: "Pets" },
  Beauty:        { ru: "Красота",            az: "Gözəllik",       en: "Beauty" },
  Sports:        { ru: "Спорт",              az: "İdman",          en: "Sports" },
  Electronics:   { ru: "Электроника",        az: "Elektronika",    en: "Electronics" },
  Charity:       { ru: "Благотворительность", az: "Xeyriyyə",      en: "Charity" },

  Alimony:       { ru: "Алименты",           az: "Aliment",        en: "Alimony" },
  "Parents Support": { ru: "Помощь родителям", az: "Valideynlərə dəstək", en: "Parents Support" },
  Maksud:        { ru: "Максуд",             az: "Maksud",         en: "Maksud" },
};

const categoryTranslationAliases: Record<string, keyof typeof categoryTranslations> = {
  "food": "Food",
  "foods": "Food",
  "grocery": "Food",
  "groceries": "Food",
  "продукты": "Food",
  "еда": "Food",
  "питание": "Food",
  "transport": "Transport",
  "transportation": "Transport",
  "транспорт": "Transport",
  "housing": "Housing",
  "rent": "Housing",
  "жильё": "Housing",
  "жилье": "Housing",
  "entertainment": "Entertainment",
  "развлечения": "Entertainment",
  "health": "Health",
  "здоровье": "Health",
  "clothing": "Clothing",
  "clothes": "Clothing",
  "одежда": "Clothing",
  "education": "Education",
  "образование": "Education",
  "restaurants": "Restaurants",
  "restaurant": "Restaurants",
  "рестораны": "Restaurants",
  "ресторан": "Restaurants",
  "communication": "Communication",
  "communications": "Communication",
  "связь": "Communication",
  "subscriptions": "Subscriptions",
  "subscription": "Subscriptions",
  "подписки": "Subscriptions",
  "подписка": "Subscriptions",
  "gifts": "Gifts",
  "gift": "Gifts",
  "подарки": "Gifts",
  "подарок": "Gifts",
  "salary": "Salary",
  "wage": "Salary",
  "зарплата": "Salary",
  "freelance": "Freelance",
  "freelancing": "Freelance",
  "фриланс": "Freelance",
  "investments": "Investments",
  "investment": "Investments",
  "инвестиции": "Investments",
  "other": "Other",
  "другое": "Other",
  "auto": "Auto",
  "car": "Auto",
  "авто": "Auto",
  "pets": "Pets",
  "pet": "Pets",
  "питомцы": "Pets",
  "beauty": "Beauty",
  "красота": "Beauty",
  "sports": "Sports",
  "sport": "Sports",
  "спорт": "Sports",
  "charity": "Charity",
  "donation": "Charity",
  "благотворительность": "Charity",
  "electronics": "Electronics",
  "электроника": "Electronics",
  "техника": "Electronics",
  "tech": "Electronics",
  "gadgets": "Electronics",
  "home": "Housing",
  "house": "Housing",
  "дом": "Housing",
  "alimony": "Alimony",
  "алименты": "Alimony",
  "parents support": "Parents Support",
  "помощь родителям": "Parents Support",
  "maksud": "Maksud",
  "максуд": "Maksud",
};

export type Lang = keyof typeof translations;
export type TranslationKey = keyof typeof translations.ru;

// ─── Context ─────────────────────────────────────────────────────────────────

type LanguageContextType = {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
  translateCategory: (categoryName: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "ru",
  setLang: () => {},
  t: (key) => translations.ru[key],
  translateCategory: (categoryName) => categoryName,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    // Try to read from localStorage first for instant load
    try {
      const stored = localStorage.getItem("cashual_lang") as Lang | null;
      if (stored && stored in translations) return stored;
    } catch {}
    return "ru";
  });

  // Sync with server-side preferredLanguage from auth.me
  const meQuery = trpc.auth.me.useQuery(undefined, {
    staleTime: 60_000,
    refetchOnWindowFocus: false,
  });

  useEffect(() => {
    const serverLang = meQuery.data?.preferredLanguage as Lang | undefined;
    if (serverLang && serverLang in translations && serverLang !== lang) {
      setLangState(serverLang);
      try {
        localStorage.setItem("cashual_lang", serverLang);
      } catch {}
    }
  // Only sync when server data arrives, not on every render
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [meQuery.data?.preferredLanguage]);

  const setLang = (newLang: Lang) => {
    setLangState(newLang);
    try {
      localStorage.setItem("cashual_lang", newLang);
    } catch {}
  };

  // REC-02: Dynamically update <html lang> attribute when language changes
  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key: TranslationKey): string => {
    return (translations[lang] as any)[key] ?? (translations.ru as any)[key] ?? key;
  };

  // Translate a canonical English category name (or known legacy alias) to the current language.
  const translateCategory = (categoryName: string): string => {
    const trimmed = categoryName.trim();
    if (!trimmed) return trimmed;
    const canonicalName = categoryTranslationAliases[trimmed.toLowerCase()] ?? trimmed;
    const entry = categoryTranslations[canonicalName];
    if (!entry) return trimmed; // fallback: keep unknown custom categories in stored English
    return entry[lang] ?? entry.en;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, translateCategory }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
